all:
  hosts:
    demo:
      ansible_host: leihs-target
      ansible_user: root
      leihs_external_hostname: demo.leihs.zhdk.ch
      db_backup_on_deploy: No
      leihs_send_mails: No
      db_backup_nigthly_enabled: No
      database_dump_restore_file_path: "{{inventory_dir}}/leihs/database/db/demo.pgbin"

# ZHdK specific settings; in particular ssl keys and certs for ZHdK HA proxy
zhdk:
  hosts:
    demo:

leihs_server:
  hosts:
    demo:
