#!/bin/sh -eu

# build the docker image and tag it with a name
docker build -t leihs/ansible-controller ./leihs/deploy

# start a temporary container from this image,
# mounting our working directory in it,
# passing through ssh-agent from host so passwordless auth works,
# then run given command
docker run --rm -it \
    -w "/leihs-instance/leihs/deploy" \
    -v "$(pwd):/leihs-instance" \
    -v "$(pwd)/tmp:/tmp/tmp" \
    -v "$(pwd)/leihs:/leihs" \
    -e S3_CACHE_ENDPOINT="${S3_CACHE_ENDPOINT:-}" \
    -e S3_CACHE_BUCKET="${S3_CACHE_BUCKET:-}" \
    -e S3_ACCESS_KEY_ID="${S3_ACCESS_KEY_ID:-}" \
    -e S3_SECRET_ACCESS_KEY="${S3_SECRET_ACCESS_KEY:-}" \
    -v "/run/host-services/ssh-auth.sock:/ssh-agent" \
    -e SSH_AUTH_SOCK="/ssh-agent" \
    leihs/ansible-controller \
    "$@"