#!/bin/bash -exu

/usr/bin/env ruby -v || exit 1 # ruby is needed to run some helper scripts

LOCAL_CACHE_DIR_RELATIVE="${LOCAL_CACHE_DIR:-"../tmp/build_cache/"}"
export LOCAL_CACHE_DIR="$(cd -- "$(dirname "${BASH_SOURCE}")" && mkdir -p "$LOCAL_CACHE_DIR_RELATIVE" && cd "$LOCAL_CACHE_DIR_RELATIVE" && pwd -P)"
source ./scripts/prepare-build-cache
export LOCAL_CACHE_DIR


cd leihs/deploy

bin/ansible-playbook \
  -i ../../hosts \
  deploy_play.yml \
  "$@"