#!/bin/bash -exu

RELEASE_NAME=$1
CHANNEL=${2:-stable}

git pull

cd leihs
git fetch
git submodule foreach --recursive 'git reset --hard HEAD'
git reset --hard "origin/${CHANNEL}"
git submodule update --recursive --init --force

cd -
git add leihs

if [[ -n "${RELEASE_NAME}" ]]; then
  git commit -m "leihs: ${RELEASE_NAME}"
else
  git commit -m "leihs: x.y.z" --edit
fi

git push
